
const Footer = () => {
    return (
        <div>
            footer 
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum officiis, temporibus officia quaerat reprehenderit doloribus illum, nulla a sapiente esse deleniti facilis ullam nihil! Provident veniam magnam explicabo atque minima tenetur, necessitatibus nihil laudantium earum recusandae dolore magni fuga deserunt voluptas consequuntur, et quasi maxime! Eos, veniam quasi odit ipsa nam illo et omnis! In cum fugit numquam ad molestiae ipsam cumque vel modi explicabo vitae iusto est similique non ducimus, nesciunt nam dolorum delectus maxime rerum porro provident exercitationem deleniti assumenda asperiores. Non consectetur numquam dicta consequuntur vitae saepe officia deserunt repudiandae libero temporibus, delectus rerum aut? Exercitationem aspernatur suscipit vitae obcaecati omnis vero fuga, tenetur totam voluptas provident rem quidem reprehenderit debitis eligendi temporibus repudiandae quia. Ullam rem neque odio ipsum sint culpa reprehenderit adipisci, earum, molestias perferendis mollitia qui assumenda ab omnis corrupti iste doloremque excepturi quis blanditiis sunt cumque expedita quidem praesentium nihil. Aliquid, beatae. Cumque dolorem quas, tempora illo nesciunt aliquid, dolor iure provident sequi ea nostrum voluptates exercitationem totam mollitia illum. Sed repudiandae totam aliquid nulla error assumenda perspiciatis officia sunt dolor repellat, voluptatibus quibusdam dolorum deserunt laborum quod. Enim, vitae maiores voluptatibus, voluptas cum omnis itaque, quibusdam blanditiis beatae nihil quasi necessitatibus vero ullam magni? Odit, veritatis optio! Voluptatibus libero ipsam, possimus molestias quia fugit quis quod et itaque deserunt aut alias repellat officiis blanditiis deleniti dolores quibusdam modi delectus facere accusantium tenetur, eos voluptates dolore! Numquam ratione ducimus, voluptates temporibus unde hic ipsam, adipisci odio inventore vitae harum a! Porro ea nihil error quaerat provident ratione, asperiores amet, eum perspiciatis consequatur eos quas similique magnam laboriosam non laborum suscipit nam, labore quasi natus blanditiis reiciendis! Rerum saepe culpa delectus sapiente recusandae cumque dolores ex ullam a eos. Corrupti reiciendis ullam voluptatibus beatae. Delectus aut ducimus nobis molestias, ullam repudiandae dolorem veritatis suscipit.</p>
        </div>
    );
};

export default Footer;